version: 0.2
env:
  variables:
    S3_BUCKET: ""
phases:
  build:
    commands:
      - npm install
      - npm run build
      - npm run zip
      - ls
      - ls dist
      - aws cloudformation package --template sam.yml --kms-key-id aws/s3 --s3-bucket $S3_BUCKET --output-template post-sam.yml
artifacts:
  files:
    - dist/handler.zip
    # The sam.yml file is not part of the lambda function. 
    # It is needed for the CodePipeline Deploy step.  
    - post-sam.yml
    - cicd-pipeline/lambda-params.json  
  discard-paths: yes
