version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run build
      - npm run zip
artifacts:
  files:
    - dist/handler.zip
    # The sam.yml file is not part of the lambda function. 
    # It is needed for the CodePipeline Deploy step.  
    - sam.yml
    - cicd-pipeline/lambda-params.json  
  discard-paths: yes
