version: 0.2
env:
  variables:
    S3_BUCKET: ""
phases:
  build:
    commands:
      - npm install
      - npm run build
      # - npm run zip
      # If bucket policy is DenyUnEncryptedObjectUploads, need to specify 
      # a --kms-key-id attribute with Arn value
      # https://medium.com/@jozeran/aws-sam-cloudformation-troubleshooting-for-lambda-deployments-60d8d3375635
      # https://forums.aws.amazon.com/thread.jspa?messageID=794124
      - aws cloudformation package --template sam.yml --s3-bucket $S3_BUCKET --output-template post-sam.yml
artifacts:
  files:
    - dist/handler.zip
    # The sam.yml file is not part of the lambda function. 
    # It is needed for the CodePipeline Deploy step.  
    - post-sam.yml
    - cicd-pipeline/lambda-params.json  
  discard-paths: yes
