version: '2'

# Will want to revisit this page when I go to setup SAM in docker-compose
# https://github.com/awslabs/aws-sam-local/issues/55

services:
  awssam-node9-awscli: 
    build: 
      context: .
      dockerfile: .docker/awssam.node9.awscli.dockerfile
    environment:
      - SAM_DOCKER_VOLUME_BASEDIR=$PWD      
    env_file:
      - .secrets/secrets.env
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
      - .:/home/node/app
    ports:
      - "3001:3000"
    command: npm start


# docker-compose build
# docker-compose run --rm --service-ports awssam-node9-awscli npm run build
# 
# https://github.com/awslabs/aws-sam-local/issues/208
# docker-compose run --rm --user root --service-ports awssam-node9-awscli /home/node/.npm-global/bin/sam local start-api -t /home/node/app/sam.yml --docker-volume-basedir $(pwd -P) --host 0.0.0.0

