AWSTemplateFormatVersion: '2010-09-09'


Parameters:
  GlobalStackName: 
    Description: 'The name of stack which this stack depends on'
    Type: String 
    Default: 'react-lambda-starter-stack'

Resources:  
  SAMStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters: 
        AppName: 
          Fn::ImportValue:
            !Sub '${GlobalStackName}-AppName'
        DomainName:
          Fn::ImportValue:
            !Sub '${GlobalStackName}-DomainName'
        FunctionName: 'friends'
        PathToHandler: ''
      TemplateURL: ./post-sam.yml

