AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Function - Friends API

Resources:

  Friends:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Events:
        ListFriends:
          Type: Api
          Properties:
            Path: /friends
            Method: get
        CreateFriend:
          Type: Api
          Properties:
            Path: /friends
            Method: post
        Friend:
          Type: Api
          Properties:
            Path: /friends/{friend}
            Method: any