AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Function - Friends API


Parameters: 
  DomainName:
    Description: Domain name for your website (example.com)
    Type: String
    Default: edbrennan.guru
  FunctionName: 
    Description: 'The name of the function'
    Type: String 
  # Link below, introduces a parameter-values parameter for the AWS-SAM-LOCAL cli commands.
  # Using this parameter to distinguish between AWS CodePipeline use of this
  # SAM file and the way AWS-SAM-LOCAL uses this SAM file.
  # AWS SAM Local is using the index.js file in dist/ folder.  CodePipeline
  # CloudFormation action will find the index.js in the root folder of the 
  # packaged ZIP file
  # https://github.com/awslabs/aws-sam-local/pull/123  
  PathToHandler: 
    Description: 'The path to index.js'
    Type: String 
    Default: ''
    AllowedValues: 
      - ''
      - dist/

Resources:

  FriendsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: 2.0
        info:
            title: !Sub "${AWS::StackName}-friends"
        basePath: /friends
        schemes: [https]
        paths:
          "/listFriends":
            get:
              produces: [application/json]
              responses: 
                description: 200 response
              x-amazon-apigateway-integration:
                httpMethod: POST # must be POST for lambda
                type: aws_proxy
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FriendsFunction.Arn}/invocations'


  FriendsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: !Sub '${PathToHandler}index.handler'
      Runtime: nodejs6.10
      CodeUri: ./dist/
      FunctionName: !Sub '${AppName}-${FunctionName}-lambda-${AWS::Region}'   
      Events:
        ListFriends:
          Type: Api
          Properties:
            Path: /listFriends
            Method: get

  BasePathMapping:
    DependsOn: FriendsFunction
    Type: 'AWS::ApiGateway::BasePathMapping'
    Properties:
      BasePath: friends
      DomainName: !Ref DomainName
      RestApiId: !Ref FriendsApi
      Stage: prod